default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check yaml files
      - id: debug-statements
        name: Check for debugger imports and breakpoint() calls
      - id: check-toml
        name: Check toml files
#      - id: check-added-large-files
#        name: Check large files

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        name: Validate commit messages
        stages: [commit-msg]
        additional_dependencies:
          - '@open-turo/commitlint-config-conventional'

  - repo: local
    hooks:
      - id: mypy
        name: Linting with mypy
        entry: |
          bash -c '
          cd backend &&
          poetry run mypy . --strict
          '
        language: system
        types:
          - python

  - repo: local
    hooks:
      - id: ruff
        name: Linting with ruff
        entry: |
          bash -c '
          cd backend &&
          poetry run ruff check . --fix &&
          poetry run ruff format .'
        language: system
        types:
          - python

  - repo: local
    hooks:
      - id: docformatter
        name: Linting with docformatter
        entry: |
          bash -c '
          cd backend &&
          poetry run docformatter . --in-place'
        language: system
        types:
          - python

  - repo: local
    hooks:
      - id: prettier
        name: Linting with prettier
        entry: |
          bash -c '
          cd frontend &&
          yarn exec prettier . --write'
        language: system
        files: \.(ts|tsx|mjs|html|json)$

  - repo: local
    hooks:
      - id: eslint
        name: Linting with eslint
        entry: |
          bash -c '
          cd frontend &&
          ./node_modules/.bin/eslint . --fix'
        language: system
        files: \.(ts|tsx|mjs|html)$
